// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvxicwvslocucajbygio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2eGljd3ZzbG9jdWNhamJ5Z2lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDkyNzcsImV4cCI6MjA2MDYyNTI3N30.nEicq36PmL8UAMJN-66MgFBQKgvbvuzclo-vZ5wYTNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);